### ISSUE TITLE
EXIOBASE conversion

### ISSUE THREAD

**Issue by Stefano-MRC** [BONSAMURAIS/EXIOBASE-conversion-software#1]
Input form RDF package group needed

**Comment by mfastudillo** [comment]
this seem to be an important. @kuzeko maybe you could help Stefano?

**Comment by kuzeko** [comment]
yes! How can I help?

**Comment by boweidema** [comment]
There is no description of the issue??

**Comment by cmutel** [comment]
This issue is impossible to understand, and therefore to fix. Closing it.
