### ISSUE TITLE
The scripts missed information on product flow origin when converting the HUSE file

### ISSUE THREAD

**Issue by kuzeko** [BONSAMURAIS/EXIOBASE-conversion-software#3]
Here column 4 in the CSV is not used  ever, this is not a problem for the SUPPLY, but it is for the USE.

https://github.com/BONSAMURAIS/EXIOBASE-conversion-software/blob/b29a20eff961c637983a69130eeb50e598aa3456/scripts/csv2rdf.py#L53

Also see example in
https://github.com/BONSAMURAIS/rdf/issues/4

**Comment by kuzeko** [comment]
This commit should export now the missing data

https://github.com/BONSAMURAIS/EXIOBASE-conversion-software/commit/c7a82b49c137896851f608ab9e1b90d54e59898c

But the instances need to be added in  the `rdf` repo

**Comment by agneta20** [comment]
We had a discussion with Bo on this and he informed that the current exiobase supply tables include additional information from trade data. This information is not necessary and if required can be updated from another data source so we don't need to have a generic class to determine location of a flow object.

**Comment by kuzeko** [comment]
From the discussion with @boweidema  :

- the separate flows from separate countries are result of an assumption/model of trade activities
- these assumptions are *not allowed* when importing data into the BONSAI triplestore
- as a result the code should "revert" this computation, and aggregate the numbers in  a single one without  location provenance information

**Comment by kuzeko** [comment]
This decision has been superseded, we can keep the "ad is" data, but then a clean (re-aggregated) dataset should also be produced as some point.
